; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#ifndef MyAppVersion
  #define MyAppVersion "0.0.0-dev"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{71968401-DB93-438D-9B91-1C18EB9A05D1}
AppName=Peace Breaker Bot
AppVersion={#MyAppVersion}
;AppVerName=Peace Breaker Bot 1.0
AppPublisher=github.com/pinheirolucas
DefaultDirName={commonpf}\Peace Breaker Bot
DefaultGroupName=Peace Breaker Bot
AllowNoIcons=yes
OutputBaseFilename=setup-peace-breaker-bot-windows
OutputDir=dist
Compression=lzma
SolidCompression=yes
PrivilegesRequired=none

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "bin\peace-breaker-bot.exe"; DestDir: "{app}"

[Icons]
Name: "{group}\Peace Breaker Bot"; Filename: "{cmd}"; Parameters: "/c ""{app}\peace-breaker-bot.exe"""
Name: "{group}\{cm:UninstallProgram,Peace Breaker Bot}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Peace Breaker Bot"; Filename: "{cmd}"; Parameters: "/c ""{app}\peace-breaker-bot.exe"""; Tasks: desktopicon

[Run]
Filename: "{app}\peace-breaker-bot.exe"; Description: "{cm:LaunchProgram,Peace Breaker Bot}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Code]
var BotSettingsPage: TInputQueryWizardPage;
procedure InitializeWizard;
begin
  BotSettingsPage := CreateInputQueryPage(wpWelcome,
    'Bot settings', 'What are the settings for the bot?',
    'Please specify the bot settings you will use to play the instants.');
  BotSettingsPage.Add('Discord username:', False);
  BotSettingsPage.Add('Bot token:', True);
end;

function GetSettingsFile(): String;
var
  Docs: String;
begin
  Docs := ExpandConstant('{userdocs}');
  Delete(Docs, Pos('Documents', Docs), length('Documents'));
  Result := Docs + '.peace-breaker-bot.yaml'
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Saved: Boolean;
begin
  Saved := SaveStringToFile(GetSettingsFile(),
    'bot:' + #13#10 +
    '  token: ' + BotSettingsPage.Values[1] + #13#10 +
    '  owner: ' + BotSettingsPage.Values[0] + #13#10 +
    'server:' + #13#10 +
    '  address: ":9001"' + #13#10,
    True);

  Result := '';
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  { Validate certain pages before allowing the user to proceed }
  if CurPageID = BotSettingsPage.ID then begin
    if BotSettingsPage.Values[0] = '' then begin
      MsgBox('You must enter your discord username.', mbError, MB_OK);
      Result := False;
    end else if BotSettingsPage.Values[1] = '' then begin
      MsgBox('You must enter the bot token.', mbError, MB_OK);
      Result := False;
    end else begin
      Result := True;
    end;
  end else
    Result := True;
end;
