name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'

      - name: Get directories to cache
        id: cache-dirs
        run: |
          echo "::set-output name=dependencies::$(go env GOPATH)/pkg/mod"
          echo "::set-output name=build::$(go env GOCACHE)"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache-dirs.outputs.dependencies }}
            ${{ steps.cache-dirs.outputs.build }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build
        run: make
